config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'posts/show'

  get '/' => 'home#top'
  get 'categories' => 'categories#categories'
  get 'communities/new' => 'communities#new'
  get 'communities/index' => 'communities#index'

  post 'communities/new' => 'communities#create'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/community.rb
class Community < ActiveRecord::Base
end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_id.rb
class UserId < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

def index

end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

def index
	@communites =Community.all
end

def new
end

def create
	@community = Community.new
	@community.name = params[:name]
	@community.category = params[:category]
	@community.save
    redirect_to communities_index_path
end

def show
end

def edit
end

def update
end

def destroy
end

end	

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/views/communities/index.html.erb
<% @communites.each do |community| %>
<p><%= community.name %></p>
<p><%= community.category %></p>
<% end %>

app/views/communities/new.html.erb
<h1>ようこそ！old age コミュニティへ！</h1>

  <h2>新規コミュニティ</h2>
  <%= form_tag communities_new_path do %>
  コミュニティ名
    <input type="text" name="name">
  詳細
    <textarea name="category"></textarea>
    <input type="submit" value="投稿する">
  <% end %>

app/views/home/top.html.erb
<h1>ようこそ！old age フォームへ！</h1>

<%= link_to "コミュニュティ作成", communities_new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>OldAge</title>

  <title>OldAgeApp</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <% if user_signed_in? %> 
          Logged in as <%= current_user.email %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "サインイン", new_user_registration_path %> |
          <%= link_to "ログイン", new_user_session_path %>
        <% end %>




<%= yield %>

</body>
</html>